import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import RainGoFall from "../comps/userInput";
import Headers from "../comps/header";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const [place,setPlace]= useState<string> ("");
   const [time,setTime]=  useState<number> (0);


   const getData = (placeData : string , timeData : number) :void => { setPlace(placeData); setTime(timeData); console.log(placeData +' '+timeData)}

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers></Headers>
      <RainGoFall transferData={getData}></RainGoFall>

     
    </>
  );
};

export default Home;
